services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  machine-learning-client:
    build: ./machine-learning-client
    container_name: machine-learning-client
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/

  web-app:
    build: ./web-app
    container_name: web-app
    depends_on:
      - mongodb
      - machine-learning-client
    ports:
      - "5002:5002"
    environment:
      MONGO_URI: mongodb://mongodb:27017/
      SECRET_KEY: secret-key
      ML_CLIENT_URL: http://machine-learning-client:5001/analyze
