services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: web-app
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=garbage_classifier
      - ML_MODEL_URL=https://serverless.roboflow.com
      - ML_MODEL_API_KEY=${ROBOFLOW_API_KEY}
      - ML_MODEL_ID=garbage-classification-3/2
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
