from pydantic import BaseModel


class CMInputs(BaseModel):
    """Input storage for the CollegeMaxxing AI service."""

    intended_university: str | None = None
    """The university that the student (user) wants to get in, which is the analysis target."""

    user_essay: str | None = None
    """The essay content provided by the student."""

    user_interview_response: str | None = None
    """The student's response to the interview questions about the intended university."""

    essay_file_name: str | None = None
    """The uploaded essay filename, stored for reference and not weighted in analysis."""

    notes: str | None = None
    """The student's personal extra notes regarding the analysis; consider when not empty."""

    sat_score: int | None = None
    """The SAT score of this student."""

    gpa: int | None = None
    """Current GPA of this student."""

    essay_pdf_bytes: bytes | None = None
    """The original bytes of the essay file for backup and database storage."""

    result: str | None = None
    """The final analysis result generated by the CMAgent."""


   