name: lint-free
on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # repeat same job for each subsystem in the following subdirectories
        subdir: [web-app, machine-learning-client]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync --dev
      - name: Lint with pylint
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          export PYTHONPATH=$PYTHONPATH:.
          pipenv run python -m pylint **/*.py --ignored-modules=pytest,flask,pytest_flask --extension-pkg-allow-list=cv2 --generated-members=cv2.* --max-line-length=200 --max-locals=100
      - name: Format with black
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          export PYTHONPATH=$PYTHONPATH:.
          pipenv run black --diff --check .
