name: lint-free
on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subdir: [web-app, machine-learning-client]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pipenv
        if: ${{ hashFiles(format('{0}/Pipfile', matrix.subdir)) != '' }}
        run: python -m pip install --upgrade pip pipenv

      - name: Install dependencies
        if: ${{ hashFiles(format('{0}/Pipfile', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          pipenv install --dev

      - name: Lint with pylint
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          pipenv run pylint app tests

      - name: Format with black
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          pipenv run black --check .