name: ml-client-lint
on: [push, pull_request]

jobs:
  lint-and-format-ml-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pipenv
        run: python -m pip install --upgrade pip pipenv

      - name: Install dependencies
        run: |
          cd machine-learning-client
          pipenv install --dev

      - name: Lint with pylint
        run: |
          cd machine-learning-client
          pipenv run pylint app tests

      - name: Format with black
        run: |
          cd machine-learning-client
          pipenv run black --check .