name: ml-client
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd machine-learning-client
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync --dev --python $(which python)
      - name: Run tests
        run: |
          cd machine-learning-client
          pipenv run pytest -v
